rebase

diff --git a/.github/workflows/publish-to-test-pypi.yml b/.github/workflows/publish-to-test-pypi.yml
--- a/.github/workflows/publish-to-test-pypi.yml
+++ b/.github/workflows/publish-to-test-pypi.yml
@@ -1,14 +1,15 @@
 name: Publish Python 🐍 distribution 📦 to TestPyPI
 
 on:
-  workflow_dispatch:  # Keep manual trigger
-    inputs:
-      version:
-        description: 'Version number (e.g. 0.0.63.dev20250111)'
-        required: true
-        type: string
-  schedule:
-    - cron: "0 0 * * *"  # Run every day at midnight
+  push:
+  # workflow_dispatch:  # Keep manual trigger
+  #   inputs:
+  #     version:
+  #       description: 'Version number (e.g. 0.0.63.dev20250111)'
+  #       required: true
+  #       type: string
+  # schedule:
+  #   - cron: "0 0 * * *"  # Run every day at midnight
 
 jobs:
   trigger-client-and-models-build:
@@ -201,43 +202,49 @@ jobs:
     runs-on: ubuntu-latest
     env:
       TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
+      FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
       TAVILY_SEARCH_API_KEY: ${{ secrets.TAVILY_SEARCH_API_KEY }}
     steps:
-    - uses: actions/checkout@v4
-      with:
-        persist-credentials: false
-    - name: Install the package
+    # - uses: actions/checkout@v4
+    #   with:
+    #     persist-credentials: false
+    # - name: Install the package
+    #   run: |
+    #     max_attempts=6
+    #     attempt=1
+    #     while [ $attempt -le $max_attempts ]; do
+    #       echo "Attempt $attempt of $max_attempts to install package..."
+    #       if pip install --no-cache --index-url https://pypi.org/simple/ --extra-index-url https://test.pypi.org/simple/ llama-stack==${{ needs.trigger-client-and-models-build.outputs.version }}; then
+    #         echo "Package installed successfully"
+    #         break
+    #       fi
+    #       if [ $attempt -ge $max_attempts ]; then
+    #         echo "Failed to install package after $max_attempts attempts"
+    #         exit 1
+    #       fi
+    #       attempt=$((attempt + 1))
+    #       sleep 10
+    #     done
+    # - name: Test the package versions
+    #   run: |
+    #     pip list | grep llama_
+    # - name: Test CLI commands
+    #   run: |
+    #     llama model list
+    #     llama stack build --list-templates
+    #     llama model prompt-format -m Llama3.2-11B-Vision-Instruct
+    #     llama stack list-apis
+    #     llama stack list-providers inference
+    #     llama stack list-providers telemetry
+    # - name: Test Notebook
+    #   run: |
+    #     pip install pytest nbval
+    #     llama stack build --template together --image-type venv
+    #     pytest -v -s --nbval-lax ./docs/notebooks/Llama_Stack_Building_AI_Applications.ipynb
+    - name: Integration tests
+      working-directory: "${{ github.workspace }}"
       run: |
-        max_attempts=6
-        attempt=1
-        while [ $attempt -le $max_attempts ]; do
-          echo "Attempt $attempt of $max_attempts to install package..."
-          if pip install --no-cache --index-url https://pypi.org/simple/ --extra-index-url https://test.pypi.org/simple/ llama-stack==${{ needs.trigger-client-and-models-build.outputs.version }}; then
-            echo "Package installed successfully"
-            break
-          fi
-          if [ $attempt -ge $max_attempts ]; then
-            echo "Failed to install package after $max_attempts attempts"
-            exit 1
-          fi
-          attempt=$((attempt + 1))
-          sleep 10
-        done
-    - name: Test the package versions
-      run: |
-        pip list | grep llama_
-    - name: Test CLI commands
-      run: |
-        llama model list
-        llama stack build --list-templates
-        llama model prompt-format -m Llama3.2-11B-Vision-Instruct
-        llama stack list-apis
-        llama stack list-providers inference
-        llama stack list-providers telemetry
-    - name: Test Notebook
-      run: |
-        pip install pytest nbval
-        llama stack build --template together --image-type venv
-        pytest -v -s --nbval-lax ./docs/notebooks/Llama_Stack_Building_AI_Applications.ipynb
-
-    # TODO: add trigger for integration test workflow & docker builds
+        pip install pytest_html
+        export FIREWORKS_API_KEY=${{ secrets.FIREWORKS_API_KEY }}
+        export TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY }}
+        pytest ${{ github.workspace }}/llama_stack/providers/tests/ -k "fireworks and together" --config=github_ci_test_config.yaml
